name: 正服Lambda更新
on:
  workflow_dispatch:  # 手动触发工作流
    inputs:
      lambda_function_name:
        description: 'lambda function name'
        required: true
jobs:
  update-lambda:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Print input parameters
        run: |
          echo "Lambda Function Name: ${{ github.event.inputs.lambda_function_name }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress Lambda function code
        run: |
          cd ./${{ github.event.inputs.lambda_function_name }}
          zip -r lambda-function.zip .

      - name: Verify Lambda function code
        run: |
          ls ./${{ github.event.inputs.lambda_function_name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-west-2

      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ github.event.inputs.lambda_function_name }} --zip-file fileb://./${{ github.event.inputs.lambda_function_name }}/lambda-function.zip
